In [4]:
import numpy as np 
print(np.__version__)


2.3.5


In [5]:
# array 

array = np.array([1,2,3,4])
array = array * 2
print(array)
print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


In [28]:
# arrays indexing
# array = np.array('A')

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','']]])

# word = array[0,0,0] + array[2,0,0] + array[2,0,0]
word = array[0,1,0] + array[0,2,2] + array[0,0,2] + array[1,0,1]

print(word)                           
#print(array.ndim)
#print(array[0][2][1])
#print(array[0,2,1])
#print(array.shape)

DICK


In [36]:
# array slicing

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# array[start:end:step]

#print(array[1:3])
#print(array[-2:-1])
#print(array[-4])
# print(array[::-2])
#print(array[0:3:2])

# selcting columns 

# print(array[:,1:3])
# print(array[:,::-1])
print(array[0:3, 1:2])
#print(array.ndim)


[[ 2]
 [ 6]
 [10]]


In [3]:
# scalar airthemtic

array = np.array([1,2,3,4])

# print(array + 1)
# print(array - 2)
# print(array * 3)
# print(array / 4)
# print(array ** 5)
# print(array % 2)



[2 3 4 5]
[-1  0  1  2]
[ 3  6  9 12]
[0.25 0.5  0.75 1.  ]
[   1   32  243 1024]
[1 0 1 0]


In [10]:
# Vectorized math func

# array = np.array([1.5,2.3,3.7,4.1])
radii = np.array([1,2,3,4])

#print(np.sqrt(array))
# print(np.round(array))
# print(np.floor(array))
# print(np.ceil(array))
# print(np.pi)
print(np.pi * radii ** 2)


[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [11]:
# Element wise airthmetic

array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [16]:
# Comparison Operators

scores = np.array([98,38,45,100,85,76,64])

scores[scores > 50] = 100
scores[scores < 50] = 0
# print(scores == 100 )
# print(scores <= 100 )
# print(scores >= 50 )
# print(scores > 50 )
# print(scores < 50 )
# print(scores != 50 )
print(scores)

[100   0   0 100 100 100 100]


In [24]:
# Broadcasting

# array1 = np.array([[1,2,3,4]])
# array2 = np.array([[1],[2],[3],[4]])

# print(array1.shape)
# print(array2.shape)
# print(array1 * array2)

# array1 = np.array([[1,2,3,4]])
# array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)
print(array1 * array2)



(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [37]:
# Aggregate function

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [5,6,7,100]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.sum(array, axis = 1))

154
12.833333333333334
26.359164545856828
694.8055555555557
1
100
0
11
[ 10  26 118]
