In [2]:
import numpy as np 
print(np.__version__)


2.3.5


In [1]:
import numpy as np
arr = np.array([20, 30, 40, 50, 60])
print("Array: ", arr)
print("Shape of array: ", arr.shape)
print("Data type of array: ", arr.dtype)
print("Size of array: ", arr.size)


Array:  [20 30 40 50 60]
Shape of array:  (5,)
Data type of array:  int64
Size of array:  5


In [2]:
print(" array first element: ", arr[0])
print(" array last element: ", arr[-1])
print(" array second to fourth element: ", arr[1:4])

print(" array + 10 = ", arr + 10)
print(" array  * 2 = ", arr * 2)
print(" array squared = ", arr ** 2)

 array first element:  20
 array last element:  60
 array second to fourth element:  [30 40 50]
 array + 10 =  [30 40 50 60 70]
 array  * 2 =  [ 40  60  80 100 120]
 array squared =  [ 400  900 1600 2500 3600]


In [3]:
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(" 2d array : ", arr2d)
print(" 2d array first row: ", arr2d[0])
print(" 2d array shape : ", arr2d.shape)
print(" 2d array row 1 , coulumn 2 :", arr2d[1][2])

 2d array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
 2d array first row:  [1 2 3]
 2d array shape :  (3, 3)
 2d array row 1 , coulumn 2 : 6


In [4]:
marks = np.array([67,54,65,89,94,87,93,76,44,37,45])

print("marks :", marks)
print(" Average marks :", np.mean(marks))
print(" Highest marks :", np.max(marks))
print(" Lowest marks :", np.min(marks))
print(" Total marks :", np.sum(marks))
print(" Sorted marks :", np.sort(marks))

marks : [67 54 65 89 94 87 93 76 44 37 45]
 Average marks : 68.27272727272727
 Highest marks : 94
 Lowest marks : 37
 Total marks : 751
 Sorted marks : [37 44 45 54 65 67 76 87 89 93 94]


In [5]:
# array 

import numpy as np

array = np.array([1,2,3,4])
array = array * 2
print(array)
print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


In [28]:
# arrays indexing

import numpy as np

# array = np.array('A')

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','']]])

# word = array[0,0,0] + array[2,0,0] + array[2,0,0]
word = array[0,1,0] + array[0,2,2] + array[0,0,2] + array[1,0,1]

print(word)                           
#print(array.ndim)
#print(array[0][2][1])
#print(array[0,2,1])
#print(array.shape)

DICK


In [36]:
# array slicing

import numpy as np

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# array[start:end:step]

#print(array[1:3])
#print(array[-2:-1])
#print(array[-4])
# print(array[::-2])
#print(array[0:3:2])

# selcting columns 

# print(array[:,1:3])
# print(array[:,::-1])
print(array[0:3, 1:2])
#print(array.ndim)


[[ 2]
 [ 6]
 [10]]


In [3]:
# scalar airthemtic

import numpy as np

array = np.array([1,2,3,4])

# print(array + 1)
# print(array - 2)
# print(array * 3)
# print(array / 4)
# print(array ** 5)
# print(array % 2)



[2 3 4 5]
[-1  0  1  2]
[ 3  6  9 12]
[0.25 0.5  0.75 1.  ]
[   1   32  243 1024]
[1 0 1 0]


In [10]:
# Vectorized math func

import numpy as np

# array = np.array([1.5,2.3,3.7,4.1])
radii = np.array([1,2,3,4])

#print(np.sqrt(array))
# print(np.round(array))
# print(np.floor(array))
# print(np.ceil(array))
# print(np.pi)
print(np.pi * radii ** 2)


[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [11]:
# Element wise airthmetic

import numpy as np

array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [16]:
# Comparison Operators

import numpy as np

scores = np.array([98,38,45,100,85,76,64])

scores[scores > 50] = 100
scores[scores < 50] = 0
# print(scores == 100 )
# print(scores <= 100 )
# print(scores >= 50 )
# print(scores > 50 )
# print(scores < 50 )
# print(scores != 50 )
print(scores)

[100   0   0 100 100 100 100]


In [24]:
# Broadcasting

import numpy as np

# array1 = np.array([[1,2,3,4]])
# array2 = np.array([[1],[2],[3],[4]])

# print(array1.shape)
# print(array2.shape)
# print(array1 * array2)

# array1 = np.array([[1,2,3,4]])
# array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)
print(array1 * array2)



(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [3]:
# Aggregate function

import numpy as np

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [5,6,7,100]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.sum(array, axis = 1))

154
12.833333333333334
26.359164545856828
694.8055555555557
1
100
0
11
[ 10  26 118]


In [16]:
# Filtering

import numpy as np

ages = np.array([[17,18,27,67,76,54,89,99,15,45],
                 [34,24,16,23,67,45,18,19,20,21]])

teenagers = ages[ ages < 18 ]
adults = ages[ (ages >= 18) & (ages < 65)]
adultss = ages[ (ages >= 18) | (ages < 65)]
even = ages[ages % 2 == 0]
odd = ages[ages % 2 != 0]
adult = np.where(ages >= 18 ,ages ,0)
adullt = np.where(ages % 2 == 0 ,ages ,-5)

print(teenagers)
print(adults)
print(adultss)
print(even)
print(odd)
print(adult)
print(adullt)

[17 15 16]
[18 27 54 45 34 24 23 45 18 19 20 21]
[17 18 27 67 76 54 89 99 15 45 34 24 16 23 67 45 18 19 20 21]
[18 76 54 34 24 16 18 20]
[17 27 67 89 99 15 45 23 67 45 19 21]
[[ 0 18 27 67 76 54 89 99  0 45]
 [34 24  0 23 67 45 18 19 20 21]]
[[-5 18 -5 -5 76 54 -5 -5 -5 -5]
 [34 24 16 -5 -5 -5 18 -5 20 -5]]


In [71]:
# Random numbers

import numpy as np

# rng = np.random.default_rng(seed = 1)

np.random.seed(seed = 1)
# # print(rng.integers(1,10))
# # print(rng.integers(low = 1 , high = 1000 , size = 10 ))
# # print(rng.integers(low = 1 , high = 100000 , size = (100,10) ))
# print(rng.integers(low = 1, high = 100 , size = (3,4)))
print(np.random.uniform(low = 1 , high = 100 , size = (3,4)))

[[42.28517847 72.31212485  1.01132311 30.93092469]
 [15.52883319 10.14152088 19.43976093 35.21051198]
 [40.27997995 54.34285667 42.50025693 68.83673054]]


In [87]:
# Shuffle 

rng = np.random.default_rng()

# array = np.array([1,2,3,4,5,6,7,8,9])
fruits = np.array(['🍎','🍌','🥭','🍍','🍊','🍓'])
# rng.shuffle(fruits)
#fruit = rng.choice(fruits)

fruits = rng.choice(fruits, size = (10,10))
print(fruits)

[['🍌' '🥭' '🍎' '🍍' '🍊' '🍍' '🍓' '🍎' '🍎' '🍌']
 ['🍎' '🍌' '🍍' '🍊' '🍊' '🍓' '🍌' '🥭' '🍌' '🍊']
 ['🍌' '🍍' '🍊' '🍍' '🍍' '🥭' '🍓' '🍊' '🥭' '🥭']
 ['🍎' '🍌' '🍓' '🍌' '🍓' '🥭' '🍎' '🍌' '🥭' '🍓']
 ['🍓' '🥭' '🍊' '🥭' '🍓' '🍓' '🍍' '🥭' '🥭' '🍌']
 ['🍓' '🍌' '🍎' '🍓' '🍌' '🍍' '🍍' '🍊' '🍍' '🥭']
 ['🍎' '🍊' '🍓' '🍎' '🍌' '🍎' '🍌' '🍎' '🍍' '🍓']
 ['🍍' '🍓' '🍊' '🍓' '🥭' '🍌' '🍓' '🍎' '🍎' '🍓']
 ['🥭' '🍎' '🍌' '🍊' '🍓' '🍎' '🍎' '🍓' '🍍' '🍎']
 ['🥭' '🥭' '🍍' '🍎' '🍎' '🍌' '🍊' '🍓' '🍍' '🥭']]
